export const RESOURCE_TYPES = [
  { id: 'dataset', title: 'Dataset', description: 'A collection of data' },
  { id: 'service', title: 'Service', description: 'A capability which receives a request and returns a response' },
  { id: 'process', title: 'Process', description: 'A process or workflow that transforms data' },
];

export const DATA_POLICIES = [
  { id: 'core', title: 'Core', description: 'Freely and openly shared without restriction' },
  { id: 'recommended', title: 'Recommended', description: 'Shared according to defined access terms' },
];

// WCMP2 contact roles — source: https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/contact-role.csv
export const CONTACT_ROLES = [
  'licensor',
  'producer',
  'processor',
  'host',
  'publisher',
];

// Full IANA link relations list (https://www.iana.org/assignments/link-relations/link-relations-1.csv)
// embedded as a static fallback because the IANA site does not send CORS headers.
// WCMP2-specific additions are fetched dynamically at runtime and appended.
// Source: https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/link-type.csv
export const LINK_RELATIONS = [
  // IANA — full list, alphabetical
  { id: 'about',                    title: 'about' },
  { id: 'acl',                      title: 'acl' },
  { id: 'alternate',                title: 'alternate' },
  { id: 'amphtml',                  title: 'amphtml' },
  { id: 'api-catalog',              title: 'api-catalog' },
  { id: 'appendix',                 title: 'appendix' },
  { id: 'apple-touch-icon',         title: 'apple-touch-icon' },
  { id: 'apple-touch-startup-image',title: 'apple-touch-startup-image' },
  { id: 'archives',                 title: 'archives' },
  { id: 'author',                   title: 'author' },
  { id: 'blocked-by',               title: 'blocked-by' },
  { id: 'bookmark',                 title: 'bookmark' },
  { id: 'c2pa-manifest',            title: 'c2pa-manifest' },
  { id: 'canonical',                title: 'canonical' },
  { id: 'chapter',                  title: 'chapter' },
  { id: 'cite-as',                  title: 'cite-as' },
  { id: 'collection',               title: 'collection' },
  { id: 'compression-dictionary',   title: 'compression-dictionary' },
  { id: 'contents',                 title: 'contents' },
  { id: 'convertedfrom',            title: 'convertedfrom' },
  { id: 'copyright',                title: 'copyright' },
  { id: 'create-form',              title: 'create-form' },
  { id: 'current',                  title: 'current' },
  { id: 'deprecation',              title: 'deprecation' },
  { id: 'describedby',              title: 'describedby' },
  { id: 'describes',                title: 'describes' },
  { id: 'disclosure',               title: 'disclosure' },
  { id: 'dns-prefetch',             title: 'dns-prefetch' },
  { id: 'duplicate',                title: 'duplicate' },
  { id: 'edit',                     title: 'edit' },
  { id: 'edit-form',                title: 'edit-form' },
  { id: 'edit-media',               title: 'edit-media' },
  { id: 'enclosure',                title: 'enclosure' },
  { id: 'external',                 title: 'external' },
  { id: 'first',                    title: 'first' },
  { id: 'geofeed',                  title: 'geofeed' },
  { id: 'glossary',                 title: 'glossary' },
  { id: 'help',                     title: 'help' },
  { id: 'hosts',                    title: 'hosts' },
  { id: 'hub',                      title: 'hub' },
  { id: 'ice-server',               title: 'ice-server' },
  { id: 'icon',                     title: 'icon' },
  { id: 'identifiers',              title: 'identifiers' },
  { id: 'index',                    title: 'index' },
  { id: 'intervalafter',            title: 'intervalafter' },
  { id: 'intervalbefore',           title: 'intervalbefore' },
  { id: 'intervalcontains',         title: 'intervalcontains' },
  { id: 'intervaldisjoint',         title: 'intervaldisjoint' },
  { id: 'intervalduring',           title: 'intervalduring' },
  { id: 'intervalequals',           title: 'intervalequals' },
  { id: 'intervalfinishedby',       title: 'intervalfinishedby' },
  { id: 'intervalfinishes',         title: 'intervalfinishes' },
  { id: 'intervalin',               title: 'intervalin' },
  { id: 'intervalmeets',            title: 'intervalmeets' },
  { id: 'intervalmetby',            title: 'intervalmetby' },
  { id: 'intervaloverlappedby',     title: 'intervaloverlappedby' },
  { id: 'intervaloverlaps',         title: 'intervaloverlaps' },
  { id: 'intervalstartedby',        title: 'intervalstartedby' },
  { id: 'intervalstarts',           title: 'intervalstarts' },
  { id: 'item',                     title: 'item' },
  { id: 'last',                     title: 'last' },
  { id: 'latest-version',           title: 'latest-version' },
  { id: 'license',                  title: 'license' },
  { id: 'linkset',                  title: 'linkset' },
  { id: 'lrdd',                     title: 'lrdd' },
  { id: 'manifest',                 title: 'manifest' },
  { id: 'mask-icon',                title: 'mask-icon' },
  { id: 'me',                       title: 'me' },
  { id: 'media-feed',               title: 'media-feed' },
  { id: 'memento',                  title: 'memento' },
  { id: 'micropub',                 title: 'micropub' },
  { id: 'modulepreload',            title: 'modulepreload' },
  { id: 'monitor',                  title: 'monitor' },
  { id: 'monitor-group',            title: 'monitor-group' },
  { id: 'next',                     title: 'next' },
  { id: 'next-archive',             title: 'next-archive' },
  { id: 'nofollow',                 title: 'nofollow' },
  { id: 'noopener',                 title: 'noopener' },
  { id: 'noreferrer',               title: 'noreferrer' },
  { id: 'opener',                   title: 'opener' },
  { id: 'original',                 title: 'original' },
  { id: 'p3pv1',                    title: 'p3pv1' },
  { id: 'payment',                  title: 'payment' },
  { id: 'pingback',                 title: 'pingback' },
  { id: 'preconnect',               title: 'preconnect' },
  { id: 'predecessor-version',      title: 'predecessor-version' },
  { id: 'prefetch',                 title: 'prefetch' },
  { id: 'preload',                  title: 'preload' },
  { id: 'prerender',                title: 'prerender' },
  { id: 'prev',                     title: 'prev' },
  { id: 'prev-archive',             title: 'prev-archive' },
  { id: 'preview',                  title: 'preview' },
  { id: 'previous',                 title: 'previous' },
  { id: 'privacy-policy',           title: 'privacy-policy' },
  { id: 'profile',                  title: 'profile' },
  { id: 'publication',              title: 'publication' },
  { id: 'rdap-active',              title: 'rdap-active' },
  { id: 'rdap-bottom',              title: 'rdap-bottom' },
  { id: 'rdap-down',                title: 'rdap-down' },
  { id: 'rdap-top',                 title: 'rdap-top' },
  { id: 'rdap-up',                  title: 'rdap-up' },
  { id: 'related',                  title: 'related' },
  { id: 'replies',                  title: 'replies' },
  { id: 'restconf',                 title: 'restconf' },
  { id: 'ruleinput',                title: 'ruleinput' },
  { id: 'search',                   title: 'search' },
  { id: 'section',                  title: 'section' },
  { id: 'self',                     title: 'self' },
  { id: 'service',                  title: 'service' },
  { id: 'service-desc',             title: 'service-desc' },
  { id: 'service-doc',              title: 'service-doc' },
  { id: 'service-meta',             title: 'service-meta' },
  { id: 'sip-trunking-capability',  title: 'sip-trunking-capability' },
  { id: 'sponsored',                title: 'sponsored' },
  { id: 'start',                    title: 'start' },
  { id: 'status',                   title: 'status' },
  { id: 'stylesheet',               title: 'stylesheet' },
  { id: 'subsection',               title: 'subsection' },
  { id: 'successor-version',        title: 'successor-version' },
  { id: 'sunset',                   title: 'sunset' },
  { id: 'tag',                      title: 'tag' },
  { id: 'terms-of-service',         title: 'terms-of-service' },
  { id: 'timegate',                 title: 'timegate' },
  { id: 'timemap',                  title: 'timemap' },
  { id: 'type',                     title: 'type' },
  { id: 'ugc',                      title: 'ugc' },
  { id: 'up',                       title: 'up' },
  { id: 'version-history',          title: 'version-history' },
  { id: 'via',                      title: 'via' },
  { id: 'webmention',               title: 'webmention' },
  { id: 'working-copy',             title: 'working-copy' },
  { id: 'working-copy-of',          title: 'working-copy-of' },
  // WCMP2 codelists (appended dynamically at runtime; listed here as fallback)
  { id: 'data',     title: 'data' },
  { id: 'deletion', title: 'deletion' },
  { id: 'station',  title: 'station' },
  { id: 'stations', title: 'stations' },
  { id: 'update',   title: 'update' },
];

export const MIME_TYPES = [
  'application/json',
  'application/geo+json',
  'application/ld+json',
  'application/xml',
  'application/gzip',
  'application/zip',
  'application/octet-stream',
  'application/pdf',
  'text/html',
  'text/csv',
  'text/plain',
  'image/png',
  'image/jpeg',
  'image/gif',
  'image/webp',
  'image/tiff',
];

// Source: https://github.com/wmo-im/wcmp2-codelists/blob/INFCOM-4/codelists/operational-status.csv
// URLs constructed as https://codes.wmo.int/wis/operational-status/<id>
// Note: this code list will be formally published after INFCOM-4 (November 2026)
export const OPERATIONAL_STATUSES = [
  {
    id: 'experimental',
    title: 'Experimental',
    presetTitle: 'First step towards operational; part of a development and production chain',
    description: 'First step in the process of becoming operational; part of a development and production chain that provides operational data.',
    url: 'https://codes.wmo.int/wis/operational-status/experimental',
  },
  {
    id: 'not-available',
    title: 'Not Available',
    presetTitle: 'Operational status is not available or not provided',
    description: 'Information on the operational status is not available or not provided.',
    url: 'https://codes.wmo.int/wis/operational-status/not-available',
  },
  {
    id: 'operational',
    title: 'Operational',
    presetTitle: 'Continuously evaluated, validated, and produced under authority responsibility',
    description: 'Continuously evaluated and validated; generated on a continuous basis with a temporal perspective under the responsibility of an authority.',
    url: 'https://codes.wmo.int/wis/operational-status/operational',
  },
  {
    id: 'pre-operational',
    title: 'Pre-Operational',
    presetTitle: 'Under review for promotion to operational; between experimental and operational',
    description: 'Under review for becoming the next operational delivery; intermediate step between Experimental and Operational.',
    url: 'https://codes.wmo.int/wis/operational-status/pre-operational',
  },
  {
    id: 'scientific',
    title: 'Scientific',
    presetTitle: 'Scientific project output, usually with a limited temporal perspective',
    description: 'Purely scientific products from scientific projects, usually with a limited temporal perspective.',
    url: 'https://codes.wmo.int/wis/operational-status/scientific',
  },
];

// Source: https://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline
export const EARTH_SYSTEM_DISCIPLINES = [
  { id: 'atmospheric-composition', title: 'Atmospheric Composition' },
  { id: 'climate', title: 'Climate' },
  { id: 'cryosphere', title: 'Cryosphere' },
  { id: 'hydrology', title: 'Hydrology' },
  { id: 'ocean', title: 'Ocean' },
  { id: 'space-weather', title: 'Space Weather' },
  { id: 'weather', title: 'Weather' },
];

export const EARTH_SYSTEM_DISCIPLINE_SCHEME =
  'http://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline';

export const TEMPORAL_RESOLUTIONS = [
  { id: 'PT1M', title: '1 minute' },
  { id: 'PT5M', title: '5 minutes' },
  { id: 'PT10M', title: '10 minutes' },
  { id: 'PT15M', title: '15 minutes' },
  { id: 'PT30M', title: '30 minutes' },
  { id: 'PT1H', title: '1 hour' },
  { id: 'PT3H', title: '3 hours' },
  { id: 'PT6H', title: '6 hours' },
  { id: 'PT12H', title: '12 hours' },
  { id: 'P1D', title: '1 day' },
  { id: 'P1W', title: '1 week' },
  { id: 'P1M', title: '1 month' },
  { id: 'P3M', title: '3 months' },
  { id: 'P1Y', title: '1 year' },
];
